using UnityEngine;

public class KeepUpright : MonoBehaviour
{
    // Update is called once per frame
    // Code generated by ChatGPT
    void LateUpdate()
    {
        transform.rotation = Quaternion.identity;
    }
}
