using UnityEngine;

public class ObjectSpawner : MonoBehaviour
{
    public Transform parent;
    public GameObject policeCar;
    public GameObject collectible;
    public GameObject spike;
    public float spawnRate = 1f;
    private float timer = 0f;
    public float positionOffset= 0.5f;
    
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        SpawnObject();
    }

    // Update is called once per frame
    void Update()
    {
        if (timer < spawnRate) 
        {
            timer += Time.deltaTime;
        } else 
        {
            SpawnObject();
            timer = 0f;
        }
    }
    
    void SpawnObject()
    {
        GameObject obj;
        float percent = Random.Range(0f,1f);
        if (percent <= 0.75f) 
        {
            obj = spike;
        } else if (percent <= 0.9f) 
        {
            obj = policeCar;
        } else
        {
            obj = collectible;
        }
        float lowestPoint = transform.position.y - positionOffset;
        float highestPoint = transform.position.y + positionOffset;
        GameObject instance = Instantiate(obj, new Vector3(transform.position.x, Random.Range(lowestPoint, highestPoint), 0), transform.rotation, parent);

        // Do not inherit scale from parent
        // The following code was generated by ChatGPT
        Vector3 parentScale = parent.lossyScale;
        instance.transform.localScale = new Vector3(
            1f / parentScale.x,
            1f / parentScale.y,
            1f / parentScale.z
);
    }
}
