using UnityEngine;
using UnityEngine.InputSystem;

public class PlayerMovement : MonoBehaviour
{
    private Rigidbody2D rb;
    private Vector2 moveInput;
    [SerializeField] private float moveSpeed = 1.6f;
    private Animator animator;
    public LogicScript logic;
    //public bool playerIsAlive = true;
    
    // Movement Bounds
    public Transform center; // center of the disc
    public float minRadius = 0.5f;
    public float maxRadius = 5.0f;


    void Start ()
    {
        rb = GetComponent<Rigidbody2D>();
        animator = GetComponentInChildren<Animator>();
        logic = GameObject.FindGameObjectWithTag("Logic").GetComponent<LogicScript>();
    }

    void Update()
    {
        // Gives a value between -1 and 1
        //horizontal = Input.GetAxisRaw("Horizontal"); // -1 is left
        //vertical = Input.GetAxisRaw("Vertical"); // -1 is down
        rb.linearVelocity = moveInput * moveSpeed;
    }

    private void OnTriggerEnter2D(Collider2D other)
    {
        if(other.gameObject.CompareTag("Coins"))
        {
            Destroy(other.gameObject);
        }
        if(other.gameObject.CompareTag("Border"))
        {
            logic.gameOver();
            //playerIsAlive = false;
            Time.timeScale = 0;
        }


    }
    
    // The code of this method was generated by ChatGPT
    void LateUpdate()
    {
        transform.rotation = Quaternion.identity;
        
        // Clamp position of player
        Vector3 offset = transform.position - center.position;
        float distance = offset.magnitude;
        
        if (distance > 0.001f)
        {
            float clampedDistance = Mathf.Clamp(distance, minRadius, maxRadius);
            transform.position = center.position + offset.normalized * clampedDistance;
        }
    }

    public void Move(InputAction.CallbackContext context)
    {
        animator.SetBool("isWalking",true);
        if(context.canceled)
        {
            animator.SetBool("isWalking", false);
            animator.SetFloat("LastInputX", moveInput.x);
            animator.SetFloat("LastInputY", moveInput.y);
        }
        moveInput = context.ReadValue<Vector2>();
        animator.SetFloat("InputX", moveInput.x);
        animator.SetFloat("InputY", moveInput.y);
    }


}

